DROP TRIGGER IF EXISTS TarkistaGPSLoki;

/* DELIMETERIKSI '/'! */
CREATE TRIGGER TarkistaGPSLoki BEFORE INSERT ON GPS
FOR EACH ROW
BEGIN
	SET @LAIVAID = NEW.ShipID;
    SET @LKM = (SELECT COUNT(*) FROM GPS WHERE ShipID = @LAIVAID);
    
    WHILE @LKM > 5 DO
    	DELETE FROM GPS WHERE ShipID = @LAIVAID AND LogID = (SELECT LogID FROM GPS WHERE ShipID = @LAIVAID ORDER BY LogID ASC LIMIT 1);
        SET @LKM = LKM - 1;
    END WHILE;
END/
